In [3]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.
 
# list_ is dataype list and array_list is numpy array.
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

# For list_
for i in list_:
    print(type(i))
    
# For array_list
for i in array_list:
    print(type(i))
       

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [7]:
#Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and array_list.

# list_ is dataype list string and array_list is numpy array integer.

# For list_
for i in list_:
    print(type(i))
    
# For array_list
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [14]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape

list_shape = np.shape(num_list)
print(list_shape)

array_shape = num_array.shape
print(array_shape)

#(ii) size

list_size = np.size(num_list)
print(list_size)

array_size = num_array.size
print(array_size)


(2, 3)
(2, 3)
6
6


In [18]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

import numpy as np

zero_array = np.zeros((3,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

import numpy as np

identity_array = np.eye(5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
